name: FilesManager-ValidationBuild

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Restore dependencies
      run: dotnet restore ./src/FilesManager.sln
    - name: Build
      run: dotnet build ./src/FilesManager.sln --no-restore
    - name: Test
      run: dotnet test ./src/FilesManager.sln --no-build --verbosity normal
